import { NgComponentOutlet } from '@angular/common';
import { Component, Type, computed, input } from '@angular/core';
import {
  LucideAmphora,
  LucideArrowLeft,
  LucideArrowRight,
  LucideBadge,
  LucideBell,
  LucideBookOpen,
  LucideBox,
  LucideBrush,
  LucideCalendar,
  LucideCalendarClock,
  LucideChartColumn,
  LucideCheck,
  LucideCoins,
  LucideCookingPot,
  LucideCheckCircle,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleAlert,
  LucideCircleCheckBig,
  LucideClock,
  LucideEye,
  LucideEyeOff,
  LucideFlag,
  LucideFlower2,
  LucideFullscreen,
  LucideFlame,
  LucideGamepad2,
  LucideGem,
  LucideGift,
  LucideHome,
  LucideImage,
  LucideInbox,
  LucideInfo,
  LucideKeyRound,
  LucideLibrary,
  LucideLayoutGrid,
  LucideList,
  LucideLockKeyhole,
  LucideLockKeyholeOpen,
  LucideLogIn,
  LucideMail,
  LucideMinimize,
  LucideMapPin,
  LucideMegaphone,
  LucideMenu,
  LucideMessageCircle,
  LucideMoon,
  LucidePackageSearch,
  LucidePause,
  LucidePartyPopper,
  LucidePencil,
  LucidePlay,
  LucidePlus,
  LucideReceipt,
  LucideRefreshCw,
  LucideSearch,
  LucideSettings,
  LucideShapes,
  LucideShieldCheck,
  LucideShoppingBag,
  LucideSparkles,
  LucideSun,
  LucideTestTube,
  LucideTicket,
  LucideTrash2,
  LucideTrophy,
  LucideUserPlus,
  LucideUserRound,
  LucideUsersRound,
  LucideWrench,
  LucideZoomIn,
  LucideZap,
  LucideX,
} from '@lucide/angular';

const ICONS = {
  amphora: LucideAmphora,
  'arrow-left': LucideArrowLeft,
  'arrow-right': LucideArrowRight,
  badge: LucideBadge,
  bell: LucideBell,
  'book-open': LucideBookOpen,
  box: LucideBox,
  brush: LucideBrush,
  calendar: LucideCalendar,
  'calendar-clock': LucideCalendarClock,
  'chart-column': LucideChartColumn,
  check: LucideCheck,
  'check-circle': LucideCheckCircle,
  'circle-alert': LucideCircleAlert,
  'circle-check': LucideCircleCheckBig,
  clock: LucideClock,
  'chevron-left': LucideChevronLeft,
  'chevron-right': LucideChevronRight,
  eye: LucideEye,
  'eye-off': LucideEyeOff,
  flag: LucideFlag,
  fullscreen: LucideFullscreen,
  flame: LucideFlame,
  'gamepad-2': LucideGamepad2,
  gem: LucideGem,
  gift: LucideGift,
  home: LucideHome,
  image: LucideImage,
  inbox: LucideInbox,
  info: LucideInfo,
  'key-round': LucideKeyRound,
  coins: LucideCoins,
  'cooking-pot': LucideCookingPot,
  'flower-2': LucideFlower2,
  library: LucideLibrary,
  'layout-grid': LucideLayoutGrid,
  list: LucideList,
  'lock-keyhole': LucideLockKeyhole,
  'lock-keyhole-open': LucideLockKeyholeOpen,
  'log-in': LucideLogIn,
  mail: LucideMail,
  minimize: LucideMinimize,
  'map-pin': LucideMapPin,
  megaphone: LucideMegaphone,
  menu: LucideMenu,
  'message-circle': LucideMessageCircle,
  moon: LucideMoon,
  'package-search': LucidePackageSearch,
  pause: LucidePause,
  'party-popper': LucidePartyPopper,
  pencil: LucidePencil,
  play: LucidePlay,
  plus: LucidePlus,
  receipt: LucideReceipt,
  refresh: LucideRefreshCw,
  search: LucideSearch,
  settings: LucideSettings,
  shapes: LucideShapes,
  'shield-check': LucideShieldCheck,
  'shopping-bag': LucideShoppingBag,
  sparkles: LucideSparkles,
  sun: LucideSun,
  'test-tube': LucideTestTube,
  ticket: LucideTicket,
  trash: LucideTrash2,
  trophy: LucideTrophy,
  'user-plus': LucideUserPlus,
  'user-round': LucideUserRound,
  'users-round': LucideUsersRound,
  wrench: LucideWrench,
  'zoom-in': LucideZoomIn,
  zap: LucideZap,
  x: LucideX,
} as const;

export type QmahIconName = keyof typeof ICONS;

@Component({
  selector: 'app-qmah-icon',
  standalone: true,
  imports: [NgComponentOutlet],
  template: '<ng-container *ngComponentOutlet="iconComponent(); inputs: iconInputs()"></ng-container>',
  styleUrl: './qmah-icon.scss',
})
export class QmahIconComponent {
  readonly name = input.required<QmahIconName>();
  readonly size = input<number | string>(18);
  readonly strokeWidth = input<number | string>(1.8);

  protected readonly iconComponent = computed<Type<unknown>>(() => ICONS[this.name()]);
  protected readonly iconInputs = computed(() => ({
    size: this.size(),
    strokeWidth: this.strokeWidth(),
  }));
}
