export interface SocialEventSummary {
  description: string;
  start: string;
  end: string;
  location: string;
  capacity: string;
}

/** Recognize the complete suffix generated by EventSocialPostSynchronizer.
 * Previews may flatten newlines. Incomplete or custom content stays untouched. */
export function parseSocialEventSummary(content: string): SocialEventSummary | null {
  const match = /(?:^|\s)活動資訊\s+時間[：:]\s*(\d{4}\/\d{2}\/\d{2} \d{2}:\d{2})\s+至\s+(\d{4}\/\d{2}\/\d{2} \d{2}:\d{2})\s+地點[：:]\s*([^\r\n]+?)\s+限額[：:]\s*(\d+\s*人|不限人數)\s*$/.exec(content);
  if (!match) return null;
  return { description: content.slice(0, match.index).trimEnd(), start: match[1], end: match[2], location: match[3].trim(), capacity: match[4] };
}
