using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using QMAH.Web.Areas.Social.Models;
using QMAH.Web.Areas.Social.Services;
using QMAH.Infrastructure.Data;
using QMAH.Web.Infrastructure.AdminNavigation;
using QMAH.Infrastructure.Models.Entities;
using QMAH.Infrastructure.Services.Social;

namespace QMAH.Web.Areas.Social.Controllers;

[Area("Social")]
[AdminNavigation("檢舉管理", 40)]
[Authorize(Policy = "Policy.Social.ManageReports")]
public sealed class SocialReportAdminController : Controller
{
    private static readonly int[] PageSizes = [10, 20, 50, 100];
    private static readonly HashSet<string> AllowedStatuses = ["PENDING", "RESOLVED", "REJECTED"];
    private static readonly HashSet<string> AllowedTargetTypes = ["POST", "COMMENT"];

    // 一次最多處理幾筆，避免有人一次勾選超大清單把整個請求卡住。
    private const int BulkReviewMaxIds = 200;

    private readonly QmahDbContext _context;
    private readonly ICurrentUserService _currentUserService;
    private readonly INotificationService _notificationService;

    public SocialReportAdminController(
        QmahDbContext context,
        ICurrentUserService currentUserService,
        INotificationService notificationService)
    {
        _context = context;
        _currentUserService = currentUserService;
        _notificationService = notificationService;
    }

    [HttpGet]
    public Task<IActionResult> Index(
        [FromQuery] ReportAdminPageViewModel filter,
        CancellationToken cancellationToken = default) =>
        Reports(filter, cancellationToken);

    [HttpGet]
    public async Task<IActionResult> Reports(
        [FromQuery] ReportAdminPageViewModel filter,
        CancellationToken cancellationToken = default)
    {
        filter.Status = Normalize(filter.Status);
        filter.TargetType = Normalize(filter.TargetType);
        filter.Keyword = string.IsNullOrWhiteSpace(filter.Keyword) ? null : filter.Keyword.Trim();
        filter.Page = Math.Max(1, filter.Page);
        filter.PageSize = PageSizes.Contains(filter.PageSize) ? filter.PageSize : 20;

        var query = _context.ContentReports.AsNoTracking();
        if (filter.Status is not null && AllowedStatuses.Contains(filter.Status))
        {
            query = query.Where(report => report.Status == filter.Status);
        }

        if (filter.TargetType is not null && AllowedTargetTypes.Contains(filter.TargetType))
        {
            query = query.Where(report => report.TargetType == filter.TargetType);
        }

        if (filter.IsAutoGenerated.HasValue)
        {
            query = query.Where(report => report.IsAutoGenerated == filter.IsAutoGenerated.Value);
        }

        if (filter.Keyword is not null)
        {
            query = query.Where(report =>
                report.Reason.Contains(filter.Keyword) ||
                (report.Detail != null && report.Detail.Contains(filter.Keyword)) ||
                (report.Resolution != null && report.Resolution.Contains(filter.Keyword)));
        }

        // 貼文、留言與檢舉人名稱在同一個投影查出，避免每筆檢舉再發一次查詢
        var totalCount = await query.CountAsync(cancellationToken);
        var totalPages = Math.Max(1, (int)Math.Ceiling(totalCount / (double)filter.PageSize));
        filter.Page = Math.Min(filter.Page, totalPages);
        var reports = await query
            .OrderByDescending(report => report.CreatedAt)
            .Select(report => new ReportListViewModel
            {
                Id = report.Id,
                TargetType = report.TargetType,
                TargetId = report.TargetId,
                TargetTitle = report.TargetType == "POST"
                    ? (_context.SocialPosts.Where(post => post.Id == report.TargetId).Select(post => post.Title).FirstOrDefault() ?? "無標題貼文")
                    : "留言檢舉",
                TargetContent = report.TargetType == "POST"
                    ? (_context.SocialPosts.Where(post => post.Id == report.TargetId).Select(post => post.Content).FirstOrDefault() ?? "內容已不存在")
                    : (_context.SocialComments.Where(comment => comment.Id == report.TargetId).Select(comment => comment.Content).FirstOrDefault() ?? "內容已不存在"),
                ReporterName = _context.UserProfiles
                    .Where(profile => profile.UserId == report.ReporterUserId)
                    .Select(profile => profile.Nickname)
                    .FirstOrDefault() ?? "未設定暱稱",
                Reason = report.Reason,
                Detail = report.Detail,
                Status = report.Status,
                Resolution = report.Resolution,
                IsAutoGenerated = report.IsAutoGenerated,
                ReviewedAt = report.ReviewedAt,
                CreatedAt = report.CreatedAt
            })
            .Skip((filter.Page - 1) * filter.PageSize)
            .Take(filter.PageSize)
            .ToListAsync(cancellationToken);

        return View("~/Areas/Social/Views/SocialAdmin/SocialReportAdmin.cshtml", new ReportAdminPageViewModel
        {
            Status = filter.Status,
            TargetType = filter.TargetType,
            Keyword = filter.Keyword,
            IsAutoGenerated = filter.IsAutoGenerated,
            Page = filter.Page,
            PageSize = filter.PageSize,
            TotalCount = totalCount,
            Reports = reports
        });
    }

    [HttpGet]
    public IActionResult Create()
    {
        ViewData["IsCreate"] = true;
        return View("~/Areas/Social/Views/SocialAdmin/EditReport.cshtml", new ReportEditViewModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ReportEditViewModel model, CancellationToken cancellationToken = default)
    {
        await ValidateTarget(model, cancellationToken);
        if (!ModelState.IsValid)
        {
            ViewData["IsCreate"] = true;
            return View("~/Areas/Social/Views/SocialAdmin/EditReport.cshtml", model);
        }

        _context.ContentReports.Add(new ContentReport
        {
            Id = Guid.NewGuid(),
            ReporterUserId = _currentUserService.GetCurrentUserId(),
            TargetType = NormalizeTargetType(model.TargetType),
            TargetId = model.TargetId,
            Reason = model.Reason.Trim(),
            Detail = string.IsNullOrWhiteSpace(model.Detail) ? null : model.Detail.Trim(),
            Status = "PENDING",
            CreatedAt = DateTime.UtcNow
        });

        await _context.SaveChangesAsync(cancellationToken);
        TempData["SuccessMessage"] = "檢舉紀錄已建立，等待審核。";
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> Edit(Guid id, CancellationToken cancellationToken = default)
    {
        var report = await _context.ContentReports.AsNoTracking().FirstOrDefaultAsync(item => item.Id == id, cancellationToken);
        if (report is null)
        {
            return NotFound();
        }

        ViewData["ReportId"] = id;
        return View("~/Areas/Social/Views/SocialAdmin/EditReport.cshtml", new ReportEditViewModel
        {
            TargetType = report.TargetType,
            TargetId = report.TargetId,
            Reason = report.Reason,
            Detail = report.Detail,
            Status = report.Status,
            Resolution = report.Resolution
        });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, ReportEditViewModel model, CancellationToken cancellationToken = default)
    {
        await ValidateTarget(model, cancellationToken);
        if (!AllowedStatuses.Contains(Normalize(model.Status) ?? string.Empty))
        {
            ModelState.AddModelError(nameof(model.Status), "不支援的檢舉狀態。");
        }

        if (!ModelState.IsValid)
        {
            ViewData["ReportId"] = id;
            return View("~/Areas/Social/Views/SocialAdmin/EditReport.cshtml", model);
        }

        var report = await _context.ContentReports.FirstOrDefaultAsync(item => item.Id == id, cancellationToken);
        if (report is null)
        {
            return NotFound();
        }

        report.TargetType = NormalizeTargetType(model.TargetType);
        report.TargetId = model.TargetId;
        report.Reason = model.Reason.Trim();
        report.Detail = string.IsNullOrWhiteSpace(model.Detail) ? null : model.Detail.Trim();
        report.Resolution = string.IsNullOrWhiteSpace(model.Resolution) ? null : model.Resolution.Trim();
        report.Status = Normalize(model.Status) ?? "PENDING";
        report.ReviewedByUserId = report.Status == "PENDING" ? null : _currentUserService.GetCurrentUserId();
        report.ReviewedAt = report.Status == "PENDING" ? null : DateTime.UtcNow;

        if (report.Status == "RESOLVED")
        {
            await HideTarget(report.TargetType, report.TargetId, cancellationToken);
        }

        await _context.SaveChangesAsync(cancellationToken);
        TempData["SuccessMessage"] = "檢舉紀錄已更新。";
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ReviewReport(
        Guid reportId,
        string status,
        string? resolution = null,
        CancellationToken cancellationToken = default)
    {
        status = Normalize(status) ?? "PENDING";
        if (!AllowedStatuses.Contains(status))
        {
            return BadRequest("不支援的檢舉審核狀態。");
        }

        var report = await _context.ContentReports.FirstOrDefaultAsync(item => item.Id == reportId, cancellationToken);
        if (report is null)
        {
            return NotFound();
        }

        var previousStatus = report.Status;
        report.Status = status;
        report.Resolution = string.IsNullOrWhiteSpace(resolution) ? null : resolution.Trim();
        report.ReviewedByUserId = status == "PENDING" ? null : _currentUserService.GetCurrentUserId();
        report.ReviewedAt = status == "PENDING" ? null : DateTime.UtcNow;

        HiddenTarget? hiddenTarget = null;
        if (status == "RESOLVED")
        {
            hiddenTarget = await HideTarget(report.TargetType, report.TargetId, cancellationToken);
        }

        // 只有狀態真的從未結案變成結案時才通知，重複按同一個按鈕不會一直發。
        if (previousStatus != status && status is "RESOLVED" or "REJECTED")
        {
            QueueReporterNotification(report);
            if (hiddenTarget is not null)
            {
                QueueAuthorHiddenNotification(hiddenTarget);
            }
        }

        // 通知與審核結果在同一次 SaveChanges 寫入：要嘛一起成功，要嘛一起失敗。
        await _context.SaveChangesAsync(cancellationToken);
        TempData["SuccessMessage"] = $"檢舉狀態已更新為：{status}。";
        return RedirectToAction(nameof(Index));
    }

    // 批次審核：後台勾選多筆檢舉（通常是同一波自動檢舉的洗版貼文）一次處理，不用一筆一筆點。
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> BulkReview(
        List<Guid> ids,
        string action,
        string? filterStatus,
        string? filterTargetType,
        string? filterKeyword,
        bool? filterIsAutoGenerated,
        int filterPage = 1,
        int filterPageSize = 20,
        CancellationToken cancellationToken = default)
    {
        var redirectRoute = new
        {
            status = filterStatus,
            targetType = filterTargetType,
            keyword = filterKeyword,
            isAutoGenerated = filterIsAutoGenerated,
            page = filterPage,
            pageSize = filterPageSize
        };

        var normalizedAction = action?.Trim().ToUpperInvariant();
        if (normalizedAction is not ("REJECT" or "HIDE" or "DELETE"))
        {
            TempData["ErrorMessage"] = "不支援的批次操作。";
            return RedirectToAction(nameof(Index), redirectRoute);
        }

        var distinctIds = ids?.Distinct().ToList() ?? [];
        if (distinctIds.Count == 0)
        {
            TempData["ErrorMessage"] = "請先勾選要處理的檢舉紀錄。";
            return RedirectToAction(nameof(Index), redirectRoute);
        }
        if (distinctIds.Count > BulkReviewMaxIds)
        {
            TempData["ErrorMessage"] = $"一次最多只能處理 {BulkReviewMaxIds} 筆，請分批操作。";
            return RedirectToAction(nameof(Index), redirectRoute);
        }

        var reports = await _context.ContentReports
            .Where(report => distinctIds.Contains(report.Id))
            .ToListAsync(cancellationToken);

        if (normalizedAction == "DELETE")
        {
            _context.ContentReports.RemoveRange(reports);
            await _context.SaveChangesAsync(cancellationToken);
            TempData["SuccessMessage"] = $"已批次刪除 {reports.Count} 筆檢舉紀錄。";
            return RedirectToAction(nameof(Index), redirectRoute);
        }

        var status = normalizedAction == "HIDE" ? "RESOLVED" : "REJECTED";
        var currentUserId = _currentUserService.GetCurrentUserId();
        var now = DateTime.UtcNow;

        // 同一篇內容可能被很多人檢舉：作者只收一次「內容已被隱藏」通知。
        var notifiedHiddenTargets = new HashSet<Guid>();
        foreach (var report in reports)
        {
            var previousStatus = report.Status;
            report.Status = status;
            report.ReviewedByUserId = currentUserId;
            report.ReviewedAt = now;

            // HIDE 等同單筆審核的「核准」：確認違規並隱藏被檢舉的貼文/留言；REJECT 只改狀態，不動目標內容。
            HiddenTarget? hiddenTarget = null;
            if (normalizedAction == "HIDE")
            {
                hiddenTarget = await HideTarget(report.TargetType, report.TargetId, cancellationToken);
            }

            if (previousStatus == status)
            {
                continue;
            }

            // 系統自動檢舉（洗版、關鍵字）沒有檢舉人，QueueReporterNotification 會自動略過。
            QueueReporterNotification(report);
            if (hiddenTarget is not null && notifiedHiddenTargets.Add(report.TargetId))
            {
                QueueAuthorHiddenNotification(hiddenTarget);
            }
        }

        await _context.SaveChangesAsync(cancellationToken);
        TempData["SuccessMessage"] = normalizedAction == "HIDE"
            ? $"已批次核准並隱藏 {reports.Count} 筆檢舉內容。"
            : $"已批次駁回 {reports.Count} 筆檢舉。";
        return RedirectToAction(nameof(Index), redirectRoute);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(Guid id, CancellationToken cancellationToken = default)
    {
        var report = await _context.ContentReports.FirstOrDefaultAsync(item => item.Id == id, cancellationToken);
        if (report is null)
        {
            return NotFound();
        }

        _context.ContentReports.Remove(report);
        await _context.SaveChangesAsync(cancellationToken);
        TempData["SuccessMessage"] = "檢舉紀錄已刪除。";
        return RedirectToAction(nameof(Index));
    }

    // 檢舉目標必須存在，否則管理者會看到無法處理的孤兒紀錄
    private async Task ValidateTarget(ReportEditViewModel model, CancellationToken cancellationToken)
    {
        model.TargetType = NormalizeTargetType(model.TargetType);

        var exists = model.TargetType == "POST"
            ? await _context.SocialPosts.AnyAsync(post => post.Id == model.TargetId, cancellationToken)
            : model.TargetType == "COMMENT" && await _context.SocialComments.AnyAsync(comment => comment.Id == model.TargetId, cancellationToken);

        if (!exists)
        {
            ModelState.AddModelError(nameof(model.TargetId), "找不到指定的貼文或留言。");
        }
    }

    // 檢舉判定為成立時只隱藏目標，不刪除原始資料，方便稽核與追查。
    // 回傳「這次真的從公開變成隱藏」的目標與作者，供通知使用；原本就已隱藏或找不到時回傳 null。
    private async Task<HiddenTarget?> HideTarget(string targetType, Guid targetId, CancellationToken cancellationToken)
    {
        if (targetType == "POST")
        {
            var post = await _context.SocialPosts.FirstOrDefaultAsync(item => item.Id == targetId, cancellationToken);
            if (post is not null)
            {
                var wasVisible = post.Status == "PUBLISHED";
                post.Status = "HIDDEN";
                post.UpdatedAt = DateTime.UtcNow;
                return wasVisible ? new HiddenTarget("POST", post.UserId, post.Title) : null;
            }
        }
        else if (targetType == "COMMENT")
        {
            var comment = await _context.SocialComments.FirstOrDefaultAsync(item => item.Id == targetId, cancellationToken);
            if (comment is not null)
            {
                var wasVisible = comment.Status == "PUBLISHED";
                comment.Status = "HIDDEN";
                comment.UpdatedAt = DateTime.UtcNow;
                return wasVisible ? new HiddenTarget("COMMENT", comment.UserId, Truncate(comment.Content, 30)) : null;
            }
        }

        return null;
    }

    // 對應前台 API 送出檢舉時的承諾：「管理員審核後會有結果通知」。
    private void QueueReporterNotification(ContentReport report)
    {
        if (report.ReporterUserId is not Guid reporterUserId)
        {
            return;
        }

        var targetLabel = report.TargetType == "COMMENT" ? "留言" : "貼文";
        var content = report.Status == "RESOLVED"
            ? $"你檢舉的{targetLabel}經審核確認違規，已被隱藏。感謝你協助維護社群。"
            : $"你檢舉的{targetLabel}經審核後未發現違規，內容將維持公開。";
        if (!string.IsNullOrWhiteSpace(report.Resolution))
        {
            content += $" 管理員說明：{report.Resolution}";
        }

        _notificationService.QueueNotification(reporterUserId, "檢舉審核結果", content);
    }

    private void QueueAuthorHiddenNotification(HiddenTarget target)
    {
        var content = target.TargetType == "COMMENT"
            ? $"你的留言「{target.Summary}」經檢舉審核確認違反社群規範，已被隱藏。"
            : $"你的貼文「{target.Summary}」經檢舉審核確認違反社群規範，已被隱藏。";
        _notificationService.QueueNotification(target.AuthorUserId, "你的內容已被隱藏", content);
    }

    private static string Truncate(string value, int maxLength) =>
        value.Length <= maxLength ? value : value[..maxLength] + "…";

    private sealed record HiddenTarget(string TargetType, Guid AuthorUserId, string Summary);

    private static string? Normalize(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : value.Trim().ToUpperInvariant();

    private static string NormalizeTargetType(string? value) =>
        AllowedTargetTypes.Contains(value?.Trim().ToUpperInvariant() ?? string.Empty)
            ? value!.Trim().ToUpperInvariant()
            : "POST";
}
